### PR TITLE
Update navigation to use CSS

### PR DESCRIPTION
**Pull request by domdomegg**
Update navbar to be done with CSS rather than image files to improve loading times, be better for people on mobile, be easier to change, be better for search engines and better for screenreaders.

Reasons:
https://ux.stackexchange.com/questions/41593/is-the-usage-of-text-embedded-in-an-image-a-bad-practice-for-very-controlled-us

### CODE REVIEW

**Comment by Prouser123** [comment]
Just wondering, do you have a live version? If not, that's fine and I'll just put it on my server, but if you do, that would be great. Thanks!

**Comment by domdomegg** [comment]
Unfortunately I'm just running a local webserver - here are some screenshots. I've also updated all the other links to use CSS as well.

Before:
screenshot from 2016-12-06 09-16-05

After:
screenshot from 2016-12-06 09-16-17

**Comment by domdomegg** [comment]
Should be all ready to merge now

**Comment by Prouser123** [comment]
Let's try it out. I'll merge now and update the site later when I have time.

**Pull request merged**
